apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-project-for-mindbox
  labels:
    app.kubernetes.io/name: depl
    app.kubernetes.io/component: web
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: depl
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: depl
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: job-web
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 80
