apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ewb-deployment-autoscaling
  labels:
    app: my-k8s-application
    env: prod
    owner: adminevgvac
spec:
  replicas: 25
  selector:
    matchLabels:
      project: mossad
  template:
    metadata:
      labels:
        project: mossad
    spec:
      containers:
        - name: mossad-web
          image: adv4000/k8sphp:version1
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: my-ewb-deployment-autoscaling
    minReplicas: 17
    maxReplicas: 25
    metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 70
      - type: Resource
        resource:
          name: memory
          targetAverageUtilization: 80