apiVersion: v1
kind: Namespace
metadata:
  name: zabbix-bft
  labels:
    name: zabbix
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
  namespace: zabbix-bft
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: web-http
  - port: 443
    targetPort: 8443
    name: web-https
  selector:
    name: zabbix-web
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
  namespace: zabbix-bft
spec:
  ports:
  - port: 10051
    targetPort: 10051
    nodePort: 31051
    name: zabbix-trapper
  - port: 162
    targetPort: 1162
    protocol: UDP
    name: snmp-trap
  selector:
    name: zabbix-server
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-java-gateway
  labels:
    app: zabbix
  namespace: zabbix-bft
spec:
  ports:
  - port: 10052
    targetPort: 10052
    name: zabbix-jmx
  selector:
    name: zabbix-java-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-service
  labels:
    app: zabbix
  namespace: zabbix-bft
spec:
  ports:
  - port: 10053
    targetPort: 10053
    name: zabbix-web-svc
  selector:
    name: zabbix-web-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-web
  labels:
    app: zabbix
    tier: zabbix-web
  namespace: zabbix-bft
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: zabbix-web
        app: zabbix
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-pgsql:alpine-6.2-latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            name: web-http
          - containerPort: 8443
            name: web-https
          resources:
            limits:
            cpu: 600m
            memory: 1024Mi
            requests:
            cpu: 200m
            memory: 400Mi
          livenessProbe:
            httpGet:
              path: /
              port: web-http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: web-http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          env:
          - name: ZBX_SERVER_NAME
            value: "Zabbix BFT"
          - name: PHP_TZ
            value: "Europe/Moscow"
          - name: DB_SERVER_HOST
            value: "172.18.35.37"
          - name: DB_SERVER_PORT
            value: "5441"
          - name: POSTGRES_USER
            value: "zabbix_dev"
          - name: POSTGRES_PASSWORD
            value: "Pass123"
          - name: POSTGRES_DB
            value: "zabbix_dev"
          - name: ZBX_DB_VERIFY_HOST
            value: "false"
          - name: ZBX_DB_CIPHER_LIST
            value: ""
#          - name: ZBX_HISTORYSTORAGEURL
#            value: ""
#          - name: ZBX_HISTORYSTORAGETYPES
#            value: ""
#          - name: ZBX_MAXEXECUTIONTIME
#            value: ""
#          - name: ZBX_MEMORYLIMIT
#            value: ""
#          - name: ZBX_POSTMAXSIZE
#            value: ""
#          - name: ZBX_UPLOADMAXFILESIZE
#            value: ""
#          - name: ZBX_MAXINPUTTIME
#            value: ""
#          - name: ZBX_SESSION_NAME
#            value: ""
#          - name: DB_DOUBLE_IEEE754
#            value: "true"
          - name: ZBX_SSO_SETTINGS
            value: "[]"
          - name: ENABLE_WEB_ACCESS_LOG
            value: "true"
          - name: DEBUG_MODE
            value: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  labels:
    app: zabbix
    tier: server
    environment: dev
  namespace: zabbix-bft
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      name: zabbix-server
      app: zabbix
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix
    spec:
      volumes:
        - name: zabbix-snmptraps
          emptyDir: {}
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:alpine-6.2-latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "4096Mi"
              cpu: "4000m"
            limits:
              memory: "8128Mi"
              cpu: "8000m"
          ports:
          - containerPort: 10051
            protocol: TCP
            name: zabbix-trapper
          readinessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 300
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 300
            periodSeconds: 60
          env:
          - name: DB_SERVER_HOST
            value: "172.18.35.37"
          - name: POSTGRES_USER
            value: "zabbix_dev"
          - name: POSTGRES_PASSWORD
            value: "Pass123"
          - name: POSTGRES_DB
            value: "zabbix_dev"
          - name: DB_SERVER_PORT
            value: "5441"
          - name: ZBX_DBTLSCIPHER
            value: ""
          - name: ZBX_DBTLSCIPHER13
            value: ""
          - name: ZBX_HISTORYSTORAGEURL
            value: ""
          - name: ZBX_HISTORYSTORAGETYPES
            value: ""
          - name: ZBX_HISTORYSTORAGEDATEINDEX
            value: "1"
          - name: ZBX_STARTREPORTWRITER
            value: "3"
          - name: ZBX_WEBSERVICEURL
            value: "http://zabbix-web-service:10053/report"
          - name: ZBX_DEBUGLEVEL
            value: "3"
          - name: ZBX_STARTPOLLERS
            value: "30"
          - name: ZBX_STARTPREPROCESSORS
            value: ""
          - name: ZBX_STARTPOLLERSUNREACHABLE
            value: ""
          - name: ZBX_STARTTRAPPERS
            value: ""
          - name: ZBX_STARTPINGERS
            value: ""
          - name: ZBX_STARTDISCOVERERS
            value: "10"
          - name: ZBX_STARTHTTPPOLLERS
            value: "10"
          - name: ZBX_IPMIPOLLERS
            value: ""
          - name: ZBX_STARTTIMERS
            value: ""
          - name: ZBX_STARTESCALATORS
            value: ""
          - name: ZBX_STARTALERTERS
            value: ""
          - name: ZBX_JAVAGATEWAY_ENABLE
            value: "true"
          - name: ZBX_JAVAGATEWAY
            value: "zabbix-java-gateway.zabbix-bft.svc"
          - name: ZBX_JAVAGATEWAYPORT
            value: "10052"
          - name: ZBX_LISTENIP
            value: "0.0.0.0"
          - name: ZBX_NODEADDRESS
            value: "172.24.18.213:31051"
          - name: ZBX_STARTJAVAPOLLERS
            value: "10"
          - name: ZBX_STARTLLDPROCESSORS
            value: ""
          - name: ZBX_STATSALLOWEDIP
            value: ""
          - name: ZBX_STARTVMWARECOLLECTORS
            value: ""
          - name: ZBX_VMWAREFREQUENCY
            value: ""
          - name: ZBX_VMWAREPERFFREQUENCY
            value: ""
          - name: ZBX_VMWARECACHESIZE
            value: ""
          - name: ZBX_VMWARETIMEOUT
            value: ""
          - name: ZBX_ENABLE_SNMP_TRAPS
            value: "true"
          - name: ZBX_HOUSEKEEPINGFREQUENCY
            value: "2"
          - name: ZBX_MAXHOUSEKEEPERDELETE
            value: "6000"
          - name: ZBX_CACHESIZE
            value: "5G"
          - name: ZBX_CACHEUPDATEFREQUENCY
            value: ""
          - name: ZBX_STARTDBSYNCERS
            value: ""
          - name: ZBX_HISTORYCACHESIZE
            value: "2048M"
          - name: ZBX_HISTORYINDEXCACHESIZE
            value: ""
          - name: ZBX_TRENDCACHESIZE
            value: ""
          - name: ZBX_VALUECACHESIZE
            value: "1000M"
          - name: ZBX_TIMEOUT
            value: "30"
          - name: ZBX_TRAPPERIMEOUT
            value: ""
          - name: ZBX_UNREACHABLEPERIOD
            value: ""
          - name: ZBX_UNAVAILABLEDELAY
            value: ""
          - name: ZBX_UNREACHABLEDELAY
            value: ""
          - name: ZBX_LOGSLOWQUERIES
            value: "7000"
          - name: ZBX_STARTPROXYPOLLERS
            value: ""
          - name: ZBX_PROXYCONFIGFREQUENCY
            value: ""
          - name: ZBX_PROXYDATAFREQUENCY
            value: ""
          - name: ZBX_EXPORTFILESIZE
            value: ""
          - name: ZBX_LOADMODULE
            value: ""
          - name: ZBX_TLSCAFILE
            value: ""
          - name: ZBX_TLSCRLFILE
            value: ""
          - name: ZBX_TLSCERTFILE
            value: ""
          - name: ZBX_TLSKEYFILE
            value: ""
          - name: ZBX_TLSCIPHERALL
            value: ""
          - name: ZBX_TLSCIPHERALL13
            value: ""
          - name: ZBX_TLSCIPHERCERT
            value: ""
          - name: ZBX_TLSCIPHERCERT13
            value: ""
          - name: ZBX_TLSCIPHERPSK
            value: ""
          - name: ZBX_TLSCIPHERPSK13
            value: ""
          - name: DEBUG_MODE
            value: "false"
          volumeMounts:
          - name: zabbix-snmptraps
            mountPath: "/var/lib/zabbix/snmptraps"
            readOnly: true
          startupProbe:
            tcpSocket:
              port: 10051
            initialDelaySeconds: 300
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 40
          livenessProbe:
            tcpSocket:
              port: 10051
            timeoutSeconds: 3
            failureThreshold: 3
            periodSeconds: 10
          securityContext:
            capabilities: {}
            privileged: false
        - name: zabbix-snmptraps
          image: zabbix/zabbix-snmptraps:alpine-6.2-latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 1162
            protocol: UDP
            name: snmp-trap
          volumeMounts:
          - name: zabbix-snmptraps
            mountPath: /var/lib/zabbix/snmptraps/
            readOnly: false
          securityContext:
            capabilities: {}
            privileged: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-java-gateway
  labels:
    app: zabbix
    tier: java
  namespace: zabbix-bft
spec:
  selector:
    matchLabels:
      name: zabbix-java-gateway
      app: zabbix
  template:
    metadata:
      labels:
        name: zabbix-java-gateway
        app: zabbix
    spec:
      containers:
        - name: zabbix-java-gateway
          image: zabbix/zabbix-java-gateway:alpine-6.2-latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10052
            protocol: TCP
            name: zabbix-java
          livenessProbe:
            tcpSocket:
              port: 10052
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 2
          env:
          - name: ZBX_START_POLLERS
            value: "10"
          - name: ZBX_TIMEOUT
            value: "30"
          - name: ZBX_DEBUGLEVEL
            value: "info"
          - name: JAVA_OPTIONS
            value: ""
          - name: DEBUG_MODE
            value: "false"
          securityContext:
            capabilities: {}
            privileged: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web-service
  labels:
    app: zabbix
    tier: web-service
  namespace: zabbix-bft
spec:
  selector:
    matchLabels:
      name: zabbix-web-service
      app: zabbix
  template:
    metadata:
      labels:
        name: zabbix-web-service
        app: zabbix
    spec:
      containers:
        - name: zabbix-web-service
          image: zabbix/zabbix-web-service:alpine-6.2-latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
            cpu: 100m
            memory: 512Mi
            requests:
            cpu: 100m
            memory: 512Mi
          ports:
          - containerPort: 10053
            protocol: TCP
            name: zabbix-web-svc
          livenessProbe:
            tcpSocket:
              port: 10053
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 2
          env:
          - name: ZBX_ALLOWEDIP
            value: "0.0.0.0/0"
          - name: ZBX_LISTENPORT
            value: "10053"
          - name: ZBX_DEBUGLEVEL
            value: "3"
          - name: ZBX_TIMEOUT
            value: "30"
          - name: ZBX_TLSACCEPT
            value: ""
          - name: ZBX_TLSCAFILE
            value: ""
          - name: ZBX_TLSCERTFILE
            value: ""
          - name: ZBX_TLSKEYFILE
            value: ""
          - name: DEBUG_MODE
            value: "false"
          securityContext:
            capabilities: {}
            privileged: false

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: zabbix-web
  namespace: zabbix-bft
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: zabbix-web
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70