---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
  spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-ewb-deployment-autoscaling-1
    minReplicas: 17
    maxReplicas: 25
    metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilizaton: 70
      - type: Resource
        resource:
          name: memory
          targetAverageUtilization: 80
