apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ewb-deployment-autoscaling-1
  labels:
    app: my-k8s-application
    env: prod
    owner: adminevgvac
spec:
  replicas: 29
  selector:
    matchLabels:
      project: mossad
  template:
    metadata:
      labels:
        project: mossad
    spec:
      containers:
        - name: mossad-web
          image: adv4000/k8sphp:version2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: adv4000-store
              mountPath: /mnt/test
    volumes:
      - name: adv4000-store
        persistentVolumeClaim:
          claimName: cephfs-pvc
          readOnly: false

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-ewb-deployment-autoscaling-1
    minReplicas: 17
    maxReplicas: 25
    metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilizaton: 70
      - type: Resource
        resource:
          name: memory
          targetAverageUtilization: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adv4000-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs