apiVersion: v1
kind: Pod
metadata:
    name: adv-project
spec:
    containers:
        - name: adv-project
          image: adv4000/k8sphp:version2
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
          
