apiVersion: apps/v1
kind: Deployment
metadata:
  name: adv-project
  labels:
    app.kubernetes.io/name: adv-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: adv-project
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adv-project
    spec:
      containers:
        - name: adv-project
          image: weaveworksdemos/shipping:0.4.8
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: adv-project
  labels:
    app.kubernetes.io/name: adv-project
spec:
  selector:
    app.kubernetes.io/name: adv-project
  ports:
    - port: 80
      targetPort: 80
#  type: LoadBalancer