apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-project
  labels:
    app: my-k8s-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      project: deploy-project
  template:
    metadata:
      labels:
        project: deploy-project
    spec:
      containers:
        - name: container-web
          image: httpd:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-project
  labels:
    env: prod
    owner: adminevgvac
spec:
  selector:
    project: kgb
  ports:
    - name: app-lissener
      protocol: TCP
      port: 80
      targetPort: 80
#  type: LoadBalancer