apiVersion: apps/v1
kind: Deployment
metadata:
  name: astra-linux
  namespace: default
  labels:
    app: astra-linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astra-linux
  template:
    metadata:
      labels:
        app: astra-linux
    spec:
      containers:
      - name: astra-linux
        image: dcksv-linux-repo.kronshtadt.ru:5000/astralinux-build-smolensk:v1
#        ports:
#            - containerPort: 80

#apiVersion: v1
#kind: Service
#metadata:
#  name: astra-linux-service
#  namespace: default
#  labels:
#    app: astra-linux
#spec:
#  type: ClusterIP
#  selector:
#    app: astra-linux
#  ports:
#  - port: 80
#    targetPort: 80
#    protocol: TCP