apiVersion: apps/v1
kind: Deployment
metadata:
  name: astra-build
  namespace: default
  labels:
    app: astra-build
spec:
#  replicas: 1
  selector:
    matchLabels:
      app: astra-build
  template:
    metadata:
      labels:
        app: astra-build
    spec:
      containers:
<<<<<<< HEAD
      - name: astra-linux
        image: dcksv-linux-repo.kronshtadt.ru:5000/astralinux-build-smolensk:v1
=======
      - name: astra-build
        image: dcksv-linux-repo.kronshtadt.ru:5000/astra-buildlinux-build-smolensk:v1
>>>>>>> parent of d94a430 (+)
#        ports:
#            - containerPort: 80

#apiVersion: v1
#kind: Service
#metadata:
#  name: astra-build-service
#  namespace: default
#  labels:
#    app: astra-build
#spec:
#  type: ClusterIP
#  selector:
#    app: astra-build
#  ports:
#  - port: 80
#    targetPort: 80
#    protocol: TCP