apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  labels:
    app.kubernetes.io/name: py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: py-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: py-app
    spec:
      containers:
        - name: py-app
          image: evgvac/py-app:v0.11
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: py-app
  labels:
    app.kubernetes.io/name: py-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: py-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005
