apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mindbox-space
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-project-for-mindbox
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80