#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: mindbox-space                 # Создаём namespace для приложения
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindbox-web-project
#  namespace: mindbox-space
  labels:
    app.kubernetes.io/name: mindbox-deploy
    app.kubernetes.io/component: web
spec:
  replicas: 4                      # Кол-во запускаемых подов
  progressDeadlineSeconds: 10         # максимальный время, допустимый для развертывания
  selector:
    matchLabels:
      app.kubernetes.io/name: mindbox-deploy
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mindbox-deploy
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: mindbox-web
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m                # Указываем максимальное потребление CPU
              memory: 128Mi
            requests:
              cpu: 100m               # Дальнейшее потребление ровное 100м, что эквивалентно 0.1 CPU
              memory: 128Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mindbox-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mindbox-deploy
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
#  - type: Resource
#    resource:
#      name: memory
#      target:
#        type: AverageValue
#        averageValue: 128Mi