---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: db2-pvc
#  namespace: ecp
#  annotations:
#    volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
#     volume.beta.kubernetes.io/storage-class: db2-sc
#    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
#spec:
#  storageClassName: 'standard'
#  storageClassName: 'longhorn'
#  volumeName: db2-pv
#  accessModes: 
#  - ReadWriteMany
#  resources:
#    requests:
#      storage: 1Gi
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: db2-pv
#  labels:
#    type: local
#spec:
#  accessModes:
#    - ReadWriteMany
#  capacity:
#    storage: 100Mi
#  hostPath:
#    path: "/mnt"

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db2-pvc
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
#     volume.beta.kubernetes.io/storage-class: db2-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi